[theme]
# PRIMARY ACCENT COLOUR FOR INTERACTIVE ELEMENTS
primaryColor = "#d33682"

# BACKGROUND COLOUR FOR MAIN CONTENT AREA
backgroundColor = "#002b36"

# BACKGROUND COLOUR FOR SIDEBAR AND MOST INTERACTIVE WIDGETS
secondaryBackgroundColor = "#586e75"

# COLOUR USED FOR MOST TEXT
textColor = "#fff"